# Generated by Django 4.0 on 2025-09-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='products',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default=True, upload_to='Images'),
        ),
    ]
